### PR TITLE
[#176014693] Rename pipeline vars - purge cdn

### PR DESCRIPTION
**Pull request by infantesimone**
### Description

This PR correctly renames the variables used in ci/cd step _purge cdn_:

- RESOURCE_GROUP_AZURE  --> PRODUCTION_RESOURCE_GROUP_NAME;
- ENDPOINT_AZURE --> PRODUCTION_CDN_ENDPOINT;
- PROFILE_NAME_CDN_AZURE --> PRODUCTION_CDN_PROFILE_NAME.

### CODE REVIEW

**Review by pasqualedevita — APPROVED** [review]
thanks @infantesimone

**Comment by pasqualedevita** [comment]
@balanza seems that in code review pipeline is missing `Static_analysis validate_api_specification`

**Comment by balanza** [comment]
> @balanza seems that in code review pipeline is missing `Static_analysis validate_api_specification`

it's ok but I just need to remove the step from the repo config

**Review by balanza — APPROVED** [review]
LGTM if such variables are set in the pipeline config. @infantesimone please double-check

**Comment by pasqualedevita** [comment]
> > @balanza seems that in code review pipeline is missing `Static_analysis validate_api_specification`
> 
> it's ok but I just need to remove the step from the repo config

ok no problem, previously I removed also `deploy` pipeline from Code review checks

**Comment by infantesimone** [comment]
verified 👍

**Pull request merged**
